name: Sync Upstream 
on:
  schedule:
    - cron: '0 0 * * 1'  # 每周一0点自动检测原仓库更新 
jobs:
  sync:
    runs-on: ubuntu-latest 
    steps:
      - uses: actions/checkout@v4 
      - name: Merge upstream 
        uses: repo-sync/github-sync@v2 
        with:
          source_repo: "Fansirsqi/Sesame-TK"
          source_branch: "main"
          destination_branch: "main"
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
